<?php

namespace App\Services\Agent;

use App\Models\AgentConfiguration;
use App\Models\AgentLearningMetric;
use App\Models\ApplicationActivityLog;
use App\Models\AutoApplication;
use App\Models\JobMatch;
use App\Models\User;
use App\Services\AI\ApplicationPreparationService;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use RuntimeException;

class AutoApplicationAgentService
{
    protected const REQUIRED_FEATURE = 'autonomous_applications';

    public function __construct(protected ApplicationPreparationService $preparationService)
    {
    }

    /**
     * Prepare an AI-enhanced application package and persist it for automation.
     */
    public function prepareForMatch(
        JobMatch $match,
        string $baseResume,
        array $screeningQuestions = [],
        array $options = []
    ): array {
        $options = array_merge([
            'auto_submit' => false,
            'submission_method' => 'manual_review',
            'resume_tone' => 'professional',
            'cover_letter_tone' => 'confident',
            'cover_letter_length' => 'medium',
            'screening_tone' => 'professional',
            'focus_skills' => [],
            'target_score' => 82,
            'force_refresh' => false,
        ], $options);

        $user = $match->user;
        $job = $match->discoveredJob;

        if (!$user || !$job) {
            throw new RuntimeException('Job match is missing required associations.');
        }

        $this->guardUserEntitlements($user, $options['auto_submit'] ?? false);

        $configuration = $user->agentConfiguration;
        if (!$configuration instanceof AgentConfiguration) {
            throw new RuntimeException('No agent configuration set up for user.');
        }

        $this->guardOperationalConstraints($configuration, $match);

        $package = $this->preparationService->prepare(
            $user,
            $job,
            $baseResume,
            $screeningQuestions,
            $options
        );

        $qualityDecision = $package['quality']['decision'] ?? 'needs_improvement';
        $status = $qualityDecision === 'ready' && $options['auto_submit']
            ? 'pending'
            : 'requires_manual';

        $payload = $package['auto_application_payload'];

        $application = DB::transaction(function () use (
            $match,
            $job,
            $user,
            $payload,
            $status,
            $options,
            $qualityDecision
        ) {
            $timestamp = now();

            $autoApplication = AutoApplication::create([
                'user_id' => $user->id,
                'job_match_id' => $match->id,
                'discovered_job_id' => $job->id,
                'customized_resume_path' => null,
                'customized_resume_content' => $payload['customized_resume_content'] ?? null,
                'cover_letter' => $payload['cover_letter'] ?? null,
                'screening_answers' => $payload['screening_answers'] ?? null,
                'custom_fields' => $this->buildCustomFields($payload, $match, $qualityDecision, $options),
                'resume_changes' => $payload['resume_changes'] ?? [],
                'keywords_optimized' => $payload['keywords_optimized'] ?? [],
                'ats_optimization_score' => $payload['ats_optimization_score'] ?? null,
                'submission_method' => $options['submission_method'],
                'status' => $status,
                'submission_response' => null,
                'submitted_at' => null,
                'application_status' => $status === 'pending' ? 'submitted' : 'submitted',
                'status_updated_at' => $timestamp,
                'status_history' => [[
                    'status' => $status === 'pending' ? 'package_prepared' : 'manual_review_required',
                    'notes' => 'Application package generated by autonomous agent.',
                    'timestamp' => $timestamp->toIso8601String(),
                ]],
                'follow_up_sent' => false,
                'follow_up_at' => null,
                'follow_up_count' => 0,
                'got_response' => false,
                'got_interview' => false,
                'got_offer' => false,
                'rejection_reason' => null,
                'feedback' => null,
            ]);

            $match->update(['auto_application_id' => $autoApplication->id]);

            return $autoApplication;
        });

        $this->postPersistUpdates($configuration, $application, $package, $match);

        return [
            'application' => $application,
            'package' => $package,
        ];
    }

    protected function guardUserEntitlements(User $user, bool $autoSubmit): void
    {
        if (method_exists($user, 'hasFeature') && !$user->hasFeature(self::REQUIRED_FEATURE)) {
            throw new RuntimeException('Current plan does not allow autonomous applications.');
        }

        if (
            $autoSubmit
            && method_exists($user, 'hasFeature')
            && !$user->hasFeature('autonomous_auto_submit')
        ) {
            throw new RuntimeException('Current plan does not allow automatic submissions.');
        }
    }

    protected function guardOperationalConstraints(AgentConfiguration $configuration, JobMatch $match): void
    {
        if (!$configuration->is_active) {
            throw new RuntimeException('Agent configuration is inactive.');
        }

        if (!$configuration->isInActiveHours()) {
            throw new RuntimeException('Agent is outside configured active hours.');
        }

        if ($configuration->hasReachedMonthlyLimit()) {
            throw new RuntimeException('Monthly auto-application limit reached.');
        }

        if (!$configuration->canApplyToday()) {
            throw new RuntimeException('Daily auto-application limit reached.');
        }

        if (!$match->isApproved()) {
            throw new RuntimeException('Job match has not been approved for application.');
        }

        if ($match->has_applied) {
            throw new RuntimeException('Job has already been applied to.');
        }
    }

    protected function buildCustomFields(
        array $payload,
        JobMatch $match,
        string $qualityDecision,
        array $options
    ): array {
        $fields = $payload['custom_fields'] ?? [];

        $fields = array_merge($fields, [
            'match_score' => $match->overall_match_score,
            'match_confidence' => $match->confidence_score,
            'decision' => $qualityDecision,
            'auto_submit_requested' => (bool) $options['auto_submit'],
            'agent_notes' => $match->decision_reasoning,
        ]);

        return $fields;
    }

    protected function postPersistUpdates(
        AgentConfiguration $configuration,
        AutoApplication $application,
        array $package,
        JobMatch $match
    ): void {
        try {
            $configuration->incrementApplicationsThisMonth();
            $configuration->updateRunSchedule();

            // Also increment the user subscription counter so the dashboard reflects agent applications
            $user = $configuration->user;
            if ($user && $user->subscription) {
                $user->subscription->increment('applications_used_this_month');
            }
        } catch (\Throwable $exception) {
            Log::warning('Failed to update agent scheduling metrics', [
                'configuration_id' => $configuration->id,
                'error' => $exception->getMessage(),
            ]);
        }

        $learning = AgentLearningMetric::firstOrNew(['user_id' => $configuration->user_id]);
        $learning->total_applications = (int) $learning->total_applications + 1;
        $learning->save();

        $autoSubmit = Arr::get($application->custom_fields, 'auto_submit_requested', false);
        $qualityDecision = $package['quality']['decision'] ?? null;
        $severity = match (true) {
            $qualityDecision === 'ready' && $autoSubmit => 'success',
            $qualityDecision === 'ready' => 'info',
            default => 'warning',
        };

        ApplicationActivityLog::log(
            $configuration->user_id,
            'application_created',
            'Prepared AI-enhanced application package.',
            $application->id,
            $application->discovered_job_id,
            [
                'quality_decision' => $qualityDecision,
                'quality_score' => $package['quality']['readiness_score'] ?? null,
                'quality_summary' => $package['quality']['summary'] ?? null,
                'ats_score' => Arr::get($package, 'ats.ats_score'),
                'resume_ats_score' => Arr::get($package, 'resume.ats_score'),
                'auto_submit' => $autoSubmit,
            ],
            $severity
        );
    }
}
