<?php

declare(strict_types=1);

namespace App\Services\ResponsibleAI;

use App\Models\AIDisclaimer;
use App\Models\AIDisclaimerAcknowledgment;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Request;

/**
 * AIDisclaimerService
 *
 * Manages AI disclaimers — what to show, when, and recording acknowledgments.
 */
class AIDisclaimerService
{
    /**
     * Get active disclaimers visible to the current authenticated user.
     *
     * @param  string  $context  AIDisclaimer::CTX_* constant
     */
    public function getForCurrentUser(string $context): \Illuminate\Database\Eloquent\Collection
    {
        $user = Auth::user();
        if (! $user) {
            return AIDisclaimer::active()
                ->forContext($context)
                ->where('show_to_candidate', true)
                ->ordered()
                ->get();
        }

        $role = $user->getRoleNames()->first() ?? 'job_seeker';
        return AIDisclaimer::getForRole($context, $role);
    }

    /**
     * Get disclaimers that still need acknowledgment by the current user.
     */
    public function getPendingAcknowledgments(
        string $context,
        ?string $subjectType = null,
        ?int $subjectId = null
    ): \Illuminate\Database\Eloquent\Collection {
        $userId = Auth::id();
        if (! $userId) {
            return collect();
        }

        $disclaimers = $this->getForCurrentUser($context)
            ->filter(fn (AIDisclaimer $d) => $d->requires_acknowledgment);

        return $disclaimers->filter(function (AIDisclaimer $d) use ($userId, $subjectType, $subjectId) {
            return ! $d->hasBeenAcknowledgedBy($userId, $subjectType, $subjectId);
        });
    }

    /**
     * Record that the current user acknowledged a disclaimer.
     */
    public function acknowledge(
        int $disclaimerId,
        ?string $subjectType = null,
        ?int $subjectId = null
    ): AIDisclaimerAcknowledgment {
        $userId = Auth::id();

        return AIDisclaimerAcknowledgment::firstOrCreate(
            [
                'disclaimer_id' => $disclaimerId,
                'user_id'       => $userId,
                'subject_type'  => $subjectType,
                'subject_id'    => $subjectId,
            ],
            [
                'ip_address'      => Request::ip(),
                'user_agent'      => substr((string) Request::userAgent(), 0, 500),
                'acknowledged_at' => now(),
            ]
        );
    }

    /**
     * Seed the default mandatory disclaimers (called on first deploy).
     */
    public static function seedDefaults(): void
    {
        $defaults = [
            [
                'key'                     => 'ai_screening_advisory',
                'title'                   => 'AI Screening — Advisory Notice',
                'body'                    => 'This screening result is generated by an AI system and is intended as a decision-support tool only. It does not constitute a final hiring decision. Human review is mandatory before any candidate is shortlisted or rejected. AI scores may reflect biases present in training data — all decisions should be validated by a qualified human reviewer.',
                'context'                 => AIDisclaimer::CTX_EMPLOYER_SCREENING,
                'severity'                => AIDisclaimer::SEV_WARNING,
                'requires_acknowledgment' => true,
                'show_to_employer'        => true,
                'show_to_candidate'       => false,
                'show_to_admin'           => true,
                'display_order'           => 1,
            ],
            [
                'key'                     => 'ai_score_candidate_notice',
                'title'                   => 'About Your AI Match Score',
                'body'                    => 'Your match score is generated by an AI that evaluates skills, experience, and job requirements. It is not a reflection of your worth as a professional. Scores are one of many inputs — hiring managers always make the final decision. If you believe your score is incorrect, you may request a manual review.',
                'context'                 => AIDisclaimer::CTX_CANDIDATE_RESULT,
                'severity'                => AIDisclaimer::SEV_INFO,
                'requires_acknowledgment' => false,
                'show_to_employer'        => false,
                'show_to_candidate'       => true,
                'show_to_admin'           => false,
                'display_order'           => 1,
            ],
            [
                'key'                     => 'ai_bias_disclaimer',
                'title'                   => 'AI Bias Awareness',
                'body'                    => 'AI systems, including this one, can reflect biases from historical data. We actively monitor for bias signals and all high-impact decisions are subject to human oversight. If you suspect a decision may be biased, please use the "Request Review" function or contact support.',
                'context'                 => AIDisclaimer::CTX_GLOBAL,
                'severity'                => AIDisclaimer::SEV_INFO,
                'requires_acknowledgment' => false,
                'show_to_employer'        => true,
                'show_to_candidate'       => true,
                'show_to_admin'           => true,
                'display_order'           => 10,
            ],
            [
                'key'                     => 'ai_rejection_notice',
                'title'                   => 'AI-Assisted Rejection — Review Required',
                'body'                    => 'This rejection was suggested by the AI screening system. Before confirming, please verify the candidate\'s full profile and ensure the rejection aligns with the job requirements and your equal opportunity obligations. Bias-correction overrides are always available.',
                'context'                 => AIDisclaimer::CTX_EMPLOYER_SCREENING,
                'severity'                => AIDisclaimer::SEV_CRITICAL,
                'requires_acknowledgment' => true,
                'show_to_employer'        => true,
                'show_to_candidate'       => false,
                'show_to_admin'           => true,
                'display_order'           => 5,
            ],
            [
                'key'                     => 'human_override_always_available',
                'title'                   => 'Human Override Always Available',
                'body'                    => 'Every AI recommendation can be overridden by a qualified human reviewer. Use the "Override AI Decision" button on any candidate profile. All overrides are logged for audit purposes. You are never obligated to follow an AI recommendation.',
                'context'                 => AIDisclaimer::CTX_EMPLOYER_SCREENING,
                'severity'                => AIDisclaimer::SEV_INFO,
                'requires_acknowledgment' => false,
                'show_to_employer'        => true,
                'show_to_candidate'       => false,
                'show_to_admin'           => true,
                'display_order'           => 2,
            ],
        ];

        foreach ($defaults as $data) {
            AIDisclaimer::firstOrCreate(['key' => $data['key']], $data);
        }
    }
}
